stages:
  - test
  - secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

sast:
  stage: test

secret_detection:
  stage: secret-detection

rust_test:
  stage: test
  image: rust:1.93.1
  cache:
    key: cargo
    paths:
      - .cargo/
      - target/
  variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  script:
    - cargo test --workspace --all-features --locked
